HibernateMovieSession HW Skarzhynets
mate-academy/hibernate-create-movie-session-hw pull request #211
Opened 2022-05-09 19:47 UTC by dSkarzh

2022-05-09 19:57 UTC, tanya-logatskaya approved these changes

2022-05-10 06:21 UTC, KseniiaMakarova requested changes

2022-05-10 06:21 UTC, KseniiaMakarova commented on src/main/java/mate/academy/model/MovieSession.java
> +    private CinemaHall cinemaHall;
let's add `@JoinColumn` annotation here
we want our column to be named `cinema_hall_id`

2022-05-10 06:21 UTC, KseniiaMakarova commented on src/main/java/mate/academy/model/MovieSession.java
> +    private LocalDateTime showTime;
and here - `show_time`
use `@Column`

2022-05-13 16:06 UTC, KseniiaMakarova requested changes
see 2 comments above

2022-05-16 15:47 UTC, Sofasmile approved these changes

2023-01-20 08:51 UTC, closed without merging