hibernate-create-movie-session-hw
mate-academy/hibernate-create-movie-session-hw pull request #308
Opened 2022-09-29 13:21 UTC by fifahater

2022-09-29 13:24 UTC, JustElvis approved these changes

2022-09-30 15:18 UTC, dSkarzh requested changes

2022-09-30 15:18 UTC, dSkarzh commented on src/main/java/mate/academy/model/CinemaHall.java
> +    }
redundant

2022-09-30 15:18 UTC, dSkarzh commented on src/main/java/mate/academy/model/MovieSession.java
> +    }
redundant

2022-09-30 15:18 UTC, dSkarzh commented on src/main/java/mate/academy/model/MovieSession.java
> +    private LocalDateTime showTime;
add join column and column annotations

2022-09-30 15:40 UTC, dSkarzh approved these changes

2024-09-17 20:16 UTC, closed without merging