Adds CinemaHall, MovieSession, and corresponding DAOs and Services
mate-academy/hibernate-create-movie-session-hw pull request #458
Opened 2023-03-05 20:48 UTC by BusyhinD

2023-03-06 14:35 UTC, uliana-andrushchuk requested changes

2023-03-06 14:35 UTC, uliana-andrushchuk commented on src/main/java/mate/academy/dao/impl/CinemaHallDaoImpl.java
> +            return getAllCinemaHallsQuery.getResultList();
please, add catch block to this method

2023-03-06 14:35 UTC, uliana-andrushchuk commented on src/main/java/mate/academy/dao/impl/MovieDaoImpl.java
> +        }
Add `catch` block

2023-03-06 14:35 UTC, uliana-andrushchuk commented on src/main/java/mate/academy/dao/impl/MovieSessionDaoImpl.java
> +                    session.createQuery("select ms from MovieSession ms "
```suggestion
                    session.createQuery("SELECT ms FROM MovieSession ms "
```
It's better to use UPPERCASE in queries

2023-03-06 14:35 UTC, uliana-andrushchuk commented on src/main/java/mate/academy/service/impl/MovieSessionServiceImpl.java
> +        return movieSessionDao.get(id).get();
It's better to use `orElseThrow()` method here to throw an exception

2023-03-07 12:50 UTC, kozhukhovsky approved these changes

2024-02-13 20:59 UTC, closed without merging