done to check
mate-academy/hibernate-create-movie-session-hw pull request #542
Opened 2023-05-09 19:05 UTC by Watxesnavo

2023-05-10 10:17 UTC, kozhukhovsky requested changes

2023-05-10 10:17 UTC, kozhukhovsky commented on src/main/java/mate/academy/dao/CinemaHallDao.java
> +    CinemaHall get(Long id);
![image](https://github.com/mate-academy/hibernate-create-movie-session-hw/assets/12864128/446fb961-4b74-49dd-882b-7b0b3a884130)

2023-05-10 10:17 UTC, kozhukhovsky commented on src/main/java/mate/academy/dao/MovieSessionDao.java
> +    MovieSession get(Long id);
![image](https://github.com/mate-academy/hibernate-create-movie-session-hw/assets/12864128/35891c28-3e4e-40bf-aa8d-c1121b14397b)

2023-05-11 11:00 UTC, okuzan approved these changes
Good job!

2024-10-31 17:36 UTC, closed without merging