hibernate-create-movie-session-hw HW solution
mate-academy/hibernate-create-movie-session-hw pull request #755
Opened 2024-01-09 19:01 UTC by luk14n

2024-01-10 10:37 UTC, Rommelua requested changes

2024-01-10 10:37 UTC, Rommelua commented on src/main/java/mate/academy/dao/impl/CinemaHallDaoImpl.java
> +            resultList.sort(Comparator.comparing(CinemaHall::getCapacity));
we should perform sorting on DB layer if we need it - not in java code

2024-01-10 10:37 UTC, Rommelua commented on src/main/java/mate/academy/dao/impl/MovieDaoImpl.java
> +            resultList.sort(Comparator.comparing(Movie::getTitle));
we should perform sorting on DB layer if we need it - not in java code

2024-01-10 10:37 UTC, Rommelua commented on src/main/java/mate/academy/dao/impl/CinemaHallDaoImpl.java
> +                Session session = sessionFactory.openSession()) {
```suggestion
        try (Session session = HibernateUtil.getSessionFactory().openSession()) {
```

2024-01-10 10:37 UTC, Rommelua commented on src/main/java/mate/academy/dao/impl/MovieDaoImpl.java
> +        try (Session session = sessionFactory.openSession()) {
```suggestion
        try (Session session = HibernateUtil.getSessionFactory().openSession()) {
```

2024-01-10 10:37 UTC, Rommelua commented on src/main/java/mate/academy/dao/impl/MovieSessionDaoImpl.java
> +            LocalDateTime endOfDay = date.atTime(23, 59, 59);
use LocalTime.MAX

2024-01-10 10:37 UTC, Rommelua commented on src/main/java/mate/academy/dao/impl/MovieSessionDaoImpl.java
> +                            + "and m.showTime <= :endOfDay "
use BETWEEN

2024-01-10 10:37 UTC, Rommelua commented on src/main/java/mate/academy/model/CinemaHall.java
> +        return Objects.hash(id, capacity, description);
delete these methods

2024-01-11 15:33 UTC, sokimaaa requested changes

2024-01-11 15:33 UTC, sokimaaa commented on src/main/java/mate/academy/dao/impl/CinemaHallDaoImpl.java
> +    }
```suggestion
    public CinemaHall add(CinemaHall cinemaHall) {
        Session session = null;
        Transaction transaction = null;
        try {
            session = HibernateUtil.getSessionFactory().openSession();
            transaction = session.beginTransaction();
            session.persist(cinemaHall);
            transaction.commit();
            return cinemaHall;
        } catch (Exception e) {
            if (transaction != null) {
                transaction.rollback();
            }
            throw new RuntimeException("Can't add cinemaHall " + cinemaHall, e);
        } finally {
            if (session != null) {
                session.close();
            }
        }
    }
```

2024-01-11 15:33 UTC, sokimaaa commented on src/main/java/mate/academy/model/MovieSession.java
> +    private CinemaHall cinemaHall;
Wrong relations between tables
```suggestion
    @OneToOne (fetch = FetchType.LAZY)
    private Movie movie;
    @OneToOne (fetch = FetchType.LAZY)
    private CinemaHall cinemaHall;
```

2024-01-11 15:33 UTC, sokimaaa commented on src/main/java/mate/academy/service/impl/CinemaHallServiceImpl.java
> +        return cinemaHallDao.get(id).get();
Never use Optional#get without the previous null-check. 
Consider reading why do we need Optional. 
```suggestion
        return cinemaHallDao.get(id).get();
```

2024-01-11 18:59 UTC, sokimaaa approved these changes

2024-01-14 09:10 UTC, closed without merging