done hw
mate-academy/hibernate-create-movie-session-hw pull request #781
Opened 2024-02-17 12:52 UTC by RomanSoproniuk

2024-02-17 17:58 UTC, olekskov requested changes

2024-02-17 17:58 UTC, olekskov commented on src/main/java/mate/academy/service/impl/CinemaHallServiceImpl.java
> +        return cinemaHallDao.get(id).get();
Working with optional we shouldn't provoke NPE. This is our chance to use proper type of exception with meaningful message
```suggestion
        return cinemaHallDao.get(id).or.ElseThrow(() -> new EntityNotFoundException("some meaningful message"));
```

2024-02-17 17:58 UTC, olekskov commented on src/main/java/mate/academy/service/impl/MovieSessionServiceImpl.java
> +    }
recheck all services for same issue

2024-02-17 17:58 UTC, olekskov commented on src/main/resources/hibernate.cfg.xml
> +</hibernate-configuration>
should be empty line in the end of file

2024-02-17 17:58 UTC, olekskov commented on src/main/java/mate/academy/dao/impl/MovieSessionDaoImpl.java
> +                    + "where ms.showTime = :date AND ms.id = :movieId", MovieSession.class);
Please try to make queries more formatted to be read easily (CASE for special words and proper line alignment)
```suggestion
            Query<MovieSession> getMovieSessionQuery = session.createQuery(
                      "FROM MovieSession ms "
                    + "WHERE ms.showTime = :date AND ms.id = :movieId", MovieSession.class);
```

2024-02-18 12:25 UTC, okuzan approved these changes

2025-03-22 20:10 UTC, closed without merging