Resolved hibernate-create-movie-session-hw Task
mate-academy/hibernate-create-movie-session-hw pull request #817
Opened 2024-04-07 10:18 UTC by DmitryLazyuka

2024-04-07 11:46 UTC, okuzan requested changes

2024-04-07 11:46 UTC, okuzan commented on src/main/java/mate/academy/service/impl/MovieSessionServiceImpl.java
> +        return movieSessionDao.get(id);
defeats the purpose of Optional. use orElseThrow + EntityNotFoundException + message + id

2024-04-07 11:46 UTC, okuzan commented on src/main/java/mate/academy/dao/MovieSessionDao.java
> +
```suggestion
```

2024-04-07 11:46 UTC, okuzan commented on src/main/java/mate/academy/dao/CinemaHallDao.java
> +
```suggestion
```

2024-04-08 11:12 UTC, MAMentorFX approved these changes

2026-06-04 08:11 UTC, closed without merging